// Generated by https://quicktype.io

export interface Contact {
    Correo:    Correo;
    RedSocial: RedSocial[];
    telefono:  Telefono[];
}

export interface Correo {
    correos: CorreoElement[];
    name:    string;
}

export interface CorreoElement {
    direccion: string;
    name:      string;
}

export interface RedSocial {
    name:  string;
    value: string;
}

export interface Telefono {
    name:   string;
    numero: number;
}
