// Generated by https://quicktype.io

export interface IProyecto {
  titulo:      string;
  background:  string;
  enlaces:     Enlaces;
  tecnologias: Tecnologia[];
}

export interface Enlaces {
  preview:     string;
  repositorio: string;
}

export interface Tecnologia {
  icon: string;
  name: string;
}

export interface IHabilidades{
  name: string;
  style: string;
  frameworks: Framework[];
  lenguajes: Lenguaje[];
}

export interface Framework{
  name: string;
  icon: string;
  alt:  string;
}

export interface SVG{
  data:string;
  fill:string;
}

export interface Lenguaje{
  name:    string;
  icon:    string;
  alt:     string;
}
